- HWIBAL/Controllers/SignInViewController.swift
- HWIBAL/Services/UserService.swift
- loginedUser를 식별할 수 있도록 SignInViewController에 전역변수로 선언했습니다.
- static으로 하던, 전역으로 하던 이렇게 관리하는게 좋은방법은 아닌거 같은데 우선 다른부분 기능 개발을 위해 풀리퀘 올렸습니다.
- 나중에 리팩토링 하면 좋을 것 같아서 라벨 달아놓겠습니다.
> [FEAT]: 👍 loginedUser 식별, UserDefaults에 저장 구현

- HWIBAL/Controllers/MyPageViewController.swift
- HWIBAL/Views/MyPageView/MyPageCustomCell.swift
- 이미지로 설정한 인디케이터를 버튼으로 변경
<br>
[적용 이미지] - MyPage
> [FIX] : 🐛 MyPage 테이블뷰 인디케이터 수정 issue #42

- HWIBAL.xcodeproj/project.pbxproj
- HWIBAL/Controllers/ReportViewController.swift
- HWIBAL/Resources/Assets.xcassets/hwibari_create.imageset/Contents.json
- HWIBAL/Views/MyPageView/MyPageView.swift
- HWIBAL/Views/ReportView/ReportEmptyView.swift
1. 최초 가입 이후 작성한 감정쓰레기가 0개인 경우 Report Page에서 보여줄 화면 구현
ReportViewController viewDidLoad에서 감쓰 개수 확인 후 0개면 ReportEmptyView 보여주고, 아니면 ReportView 보여줌
> [FEAT] : 👍 ReportPage 감정쓰레기 0개 시 보여줄 화면 추가 구현 Issue #29

- HWIBAL.xcodeproj/project.pbxproj
- HWIBAL/Controllers/DetailViewController.swift
- HWIBAL/Views/DetailView/EmptyDetailView.swift
|                          라이트모드                          |                           다크모드                           |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
| <img width="300" alt="image" src="https://github.com/hidaehyunlee/HWIBAL/assets/37580034/77acedb1-88ca-43f8-aa3e-6e332910d922"> | <img width="300" alt="image" src="https://github.com/hidaehyunlee/HWIBAL/assets/37580034/9e943a55-d6ee-4270-b4f8-4668299eaefb"> |
- issue #28 대응
> [FEAT]: 👍 EmptyDetailView 구현

- HWIBAL/Views/ReportView/ReportDayOfTheWeekCell.swift
* 기기 해상도 변경 시 셀 내부 컴포넌트들의 마진이 안맞아서 MaxDay label 사이즈를 동적으로 변경되도록 수정하였습니다.
* Issue #72
> [FIX] : 🐛  Report 두번째 셀 MaxDay label 사이즈 조정 Issue #72

- HWIBAL/Views/SignInView/SignInView.swift
* 휘발이 이미지랑 타이틀, 버튼 묶어서 스택뷰로 leading offset 수정
* 타이틀 기기 변경 시 내용 짤리는 문제 해결
* issue #73 #79  대응
|                          라이트모드                          |                           다크모드                           |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
| <img width="300" alt="image" src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/c66f13b7-654c-465c-a18b-cf51183804e5"> | <img width="300" alt="image" src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/5f26b6f6-18f7-4254-8a02-c983c0339fb0"> |
> [FIX] : 🐛  컴포넌트 별 오토레이아웃 수정, 타이틀 컬러 변경 Issue #73 #79

- HWIBAL/Controllers/MyPageViewController.swift
- HWIBAL/Views/MyPageView/MyPageView.swift
* 테이블뷰 높이 수정
* View, 테이블 뷰 위치 수정
* 회원탈퇴 버튼 bottom 40 간격으로 수정
* MyPage SE 시뮬테스트 후 충돌나는 레이아웃 해결
<br>
**[시뮬레이션]**
|                          SE                          |                           XS                           |                           14 Pro                           |
| :------------------------------------: | :------------------------------------: |:------------------------------------: |
| <img width="300" alt="image" src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/a6f4a508-99cd-4594-83b1-ccc44edcdb39"> | <img width="300" alt="image" src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/20ecaedc-8723-4e00-b5f7-9296507686f7"> | <img width="300" alt="image" src="https://github.com/hidaehyunlee/HWIBAL/assets/53863005/6bec9a15-f9f5-4d7c-a2c1-4623eb447902"> …
> [FIX] : 🐛 MyPage 오토레이아웃 충돌 해결

- HWIBAL.xcodeproj/project.pbxproj
- HWIBAL/Controllers/MyPageViewController.swift
- HWIBAL/Resources/AppDelegate.swift
- HWIBAL/Services/EmotionTrashService.swift
- HWIBAL/Services/NotificationService.swift
> [FIX] : 🐛 자동 휘발 로직 수정(Timer 적용)

- HWIBAL.xcodeproj/project.pbxproj
- HWIBAL/Controllers/MyPageViewController.swift
- HWIBAL/Resources/AppDelegate.swift
- HWIBAL/Services/EmotionTrashService.swift
- HWIBAL/Services/NotificationService.swift
Reverts hidaehyunlee/HWIBAL#94
> Revert "[FIX] : 🐛 자동 휘발 로직 수정(Timer 적용)"

- HWIBAL/Controllers/HomeViewController.swift
- HWIBAL/Views/HomeView/HomeView.swift
> [FIX] : 🐛  툴팁 디자인 수정

- HWIBAL.xcodeproj/project.pbxproj
- HWIBAL/Controllers/MyPageViewController.swift
- HWIBAL/Controllers/SignInViewController.swift
- HWIBAL/Models/User+CoreDataClass.swift
- HWIBAL/Services/SignInService.swift
- HWIBAL/Services/UserService.swift
- HWIBAL/Views/MyPageView/MyPageCustomCell.swift
- Model.xcdatamodeld/Model.xcdatamodel/contents
Reverts hidaehyunlee/HWIBAL#97
> Revert "[FIX] : 🐛 User Model 수정"

- HWIBAL.xcodeproj/project.pbxproj
- HWIBAL/Controllers/MyPageViewController.swift
- HWIBAL/Controllers/SignInViewController.swift
- HWIBAL/Models/User+CoreDataClass.swift
- HWIBAL/Services/SignInService.swift
- HWIBAL/Services/UserService.swift
- HWIBAL/Views/MyPageView/MyPageCustomCell.swift
- Model.xcdatamodeld/Model.xcdatamodel/contents
Reverts hidaehyunlee/HWIBAL#100
> Revert "Revert "[FIX] : 🐛 User Model 수정""

- HWIBAL/Services/ReportService.swift
- HWIBAL/Views/MyPageView/MyPageView.swift
- HWIBAL/Views/ReportView/ReportSummaryCell.swift
* 평균과 비교 -> 지난주와 비교로 변경
| 마이페이지 | 리포트 첫번째 셀 |
|:---:|:---:|
|![image](https://github.com/hidaehyunlee/HWIBAL/assets/53863005/0aa305ad-9df8-41a3-8cc0-4b2416ae1128)|![image](https://github.com/hidaehyunlee/HWIBAL/assets/53863005/71a9e174-7e41-4b9d-8fdd-cf0da92ad1e6)|
> [FEAT] : 👍 Report 요약 -> 지난주/이번주 비교로 변경

- HWIBAL/Controllers/MyPageViewController.swift
- HWIBAL/Resources/AppDelegate.swift
- HWIBAL/Resources/SceneDelegate.swift
- HWIBAL/Services/EmotionTrashService.swift
- HWIBAL/Services/NotificationService.swift
- HWIBAL/Services/UserService.swift
앱이 포그라운드로 진입했을 때 기존 코드가 실행이 안되는 이유를 찾았습니다...
AppDelegate에서 실행되는게 아니라 SceneDelegate에서 실행해야 하더라고요...
iOS 13 이후부터는 SceneDelegate에서 기능이 수행되는걸 이제 알았네요ㅠㅋㅋㅋㅋ
<br>
* 삭제 주기는 자정으로 세팅해두었습니다.
<br>
> [FIX] : 🐛 자동휘발주기 세팅 및 Noti 수정 완료(테스트 완료)

- HWIBAL/Controllers/DetailViewController.swift
- HWIBAL/Controllers/ImageModalViewController.swift
- HWIBAL/Views/DetailView/EmotionTrashCell.swift
- HWIBAL/Views/DetailView/ImageModalView.swift
- 배포 이후, 업데이트를 통해 컬렉션뷰로 바꿀 예정입니다.
> [FIX]: 🐛 modalViewController를 cell 내에서 생성(임시)

- HWIBAL.xcodeproj/project.pbxproj
- HWIBAL/Views/Shared/Extension+UIColor.swift
- HWIBAL/Views/SignInView/SignInView.swift
* UIColor 확장파일로 화면모드 확인 로직 추가
| 라이트모드 | 다크모드 |
|:--:|:--:|
|![image](https://github.com/hidaehyunlee/HWIBAL/assets/53863005/88aa67ef-d4e9-4ff0-a0e1-0f2bf4287884)|![image](https://github.com/hidaehyunlee/HWIBAL/assets/53863005/8e2031ea-1bae-44b4-8479-79f36c8a15a3)|
> [FEAT] : 👍 애플로그인 화면모드에 따라 버튼스타일 변경

- HWIBAL/Controllers/DetailViewController.swift
- HWIBAL/Views/DetailView/DetailView.swift
- HWIBAL/Views/DetailView/EmotionTrashCell.swift
- 제 시뮬에서 녹음이 안돼서 테스트를 못해봤습니다. 로직은 맞는거같은데 테스트용으로 pr 올려요.. ㅜㅜ
- playPauseButton 은 기본 hidden 이고, Recording에 filePath가 존재 할 때만 (131번째줄) isHidden = false 됩니다.
- tag를 이용해서 인덱스를 전달하고, playPauseButtonTapped에서 tag로 인덱스를 식별해 해당 item의 filePath로 플레이어를 생성합니다.
> [FEAT]: 👍  Recording.filePath 이용해 오디오 플레이어 생성

- HWIBAL/Controllers/MyPageViewController.swift
- HWIBAL/Views/DetailView/DetailView.swift
- HWIBAL/Views/DetailView/EmotionTrashCell.swift
> [FiX] : 🐛 법적 고지 링크 및 DetailView 레이아웃 수정

- HWIBAL/Controllers/DetailViewController.swift
- HWIBAL/Views/DetailView/DetailView.swift
- HWIBAL/Views/DetailView/EmotionTrashCell.swift
- item 떨어지는 문제 해결
- 개별삭제 기능 삭제
- v1.1.0 에서 cell 내부 컴포넌트로 넣을 지 고민하기
- 맨 처음으로 버튼 width 추가
> [[FIX]: 🐛 DetailView v1.0.1 기준으로 수정

- HWIBAL/Views/HomeView/HomeView.swift
> [FIX] : 🐛 앱 설치후 최초 실행시에만 툴팁뷰 노출되도록 수정, emotionCount가 0일때 '다,휘발'시 경고창 표시

- HWIBAL/Controllers/DetailViewController.swift
- HWIBAL/Views/CreatePageView/CreatePageView.swift
> [FIX] : 🐛 textview fontsize 16변경

- HWIBAL.xcodeproj/project.pbxproj
- HWIBAL/Controllers/CreatePageViewController.swift
- HWIBAL/Views/CreatePageView/CreatePageView.swift
https://github.com/hidaehyunlee/HWIBAL/assets/113526669/f1ce4241-f74a-4d41-a98e-613096a661ce
> [FIX] : 🐛 실기기test시 이미지 첨부 버그 해결

- HWIBAL/Controllers/LaunchScreenView.swift
다크모드 적용
https://github.com/hidaehyunlee/HWIBAL/assets/139306158/58f53b4d-5d10-4a48-83d2-64073c12b726
다크모드 미적용
https://github.com/hidaehyunlee/HWIBAL/assets/139306158/70bf7843-bd6f-4a51-929c-10ecfb6d18b6
감사합니다
> [FIX] : 🐛 런치스크린 시스템컬러 적용

- HWIBAL.xcodeproj/project.pbxproj
- HWIBAL/Controllers/CreatePageViewController.swift
- HWIBAL/Controllers/DetailViewController.swift
- HWIBAL/Services/AudioPlayerService.swift
- HWIBAL/Views/DetailView/EmotionTrashCell.swift
> [FEAT]: 👍  AudioPlayerService 구현
